using PMPlatform.Application.Common.Auditing;
using PMPlatform.Application.Features.IdentityAccess.Contracts.Administration;
using PMPlatform.Application.Features.Reports.Contracts;
using PMPlatform.Domain.Reports;

namespace PMPlatform.Application.Features.Reports;

/// <summary>
/// An accepted export request becomes a REQUESTED job (FG-02 §10.1; R-7), for a published report or an explorer composition alike. The requester's
/// key makes the request idempotent (US-RPT-SYS-038, R-39): the same key with the same request answers with the job it made, with a different
/// request it is refused. Nothing is read here: the job is checked again and generated by <see cref="IReportMaintenance"/>.
/// </summary>
internal sealed class ReportJobRequests(IReportRepository repository, IAuditTrail audit, TimeProvider timeProvider)
{
    public async Task<AdministrationResult<ReportExportOutcome>> RequestAsync(
        Guid callerId, ReportJobKind kind, ReportDefinition? definition, ReportRequestSnapshot snapshot, ReportExportInput output, Guid idempotencyKey, Guid correlationId,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(snapshot);
        ArgumentNullException.ThrowIfNull(output);
        if (await ReplayAsync(callerId, kind, definition, snapshot, output, idempotencyKey, cancellationToken).ConfigureAwait(false) is { } replayed)
        {
            return replayed;
        }

        DateTimeOffset now = timeProvider.GetUtcNow();
        ReportJob job = new()
        {
            Id = Guid.CreateVersion7(now),
            Kind = kind,
            ReportDefinitionId = definition?.Id,
            RequestedByUserId = callerId,
            RequestedAt = now,
            ExportFormat = output.Format,
            ReportLanguage = output.Language,
            CorrelationId = correlationId,
            IdempotencyKey = idempotencyKey,
            Status = ReportJobStatus.Requested,
            RequestSnapshot = snapshot.ToJson(),
            CreatedAt = now,
            CreatedBy = callerId,
            UpdatedAt = now,
            UpdatedBy = callerId,
        };
        repository.Add(job);
        audit.Stage(ReportAudit.ExportRequested(job, definition?.Code, snapshot.Columns.Count));
        return await repository.SaveAsync(cancellationToken).ConfigureAwait(false) switch
        {
            ReportSaveOutcome.Saved => new ReportExportOutcome(ReportMapping.ToDetail(job, definition?.Code, null), Replayed: false),

            // The same key, sent twice at once: the other request made the job.
            ReportSaveOutcome.Duplicate => await ReplayAsync(callerId, kind, definition, snapshot, output, idempotencyKey, cancellationToken).ConfigureAwait(false)
                                           ?? AdministrationError.PreconditionFailed,
            ReportSaveOutcome.ConcurrencyConflict => AdministrationError.PreconditionFailed,
            _ => throw new InvalidOperationException("Unknown save outcome."),
        };
    }

    private async Task<AdministrationResult<ReportExportOutcome>?> ReplayAsync(
        Guid callerId, ReportJobKind kind, ReportDefinition? definition, ReportRequestSnapshot snapshot, ReportExportInput output, Guid idempotencyKey,
        CancellationToken cancellationToken)
    {
        if (await repository.FindJobByKeyAsync(callerId, idempotencyKey, cancellationToken).ConfigureAwait(false) is not { } existing)
        {
            return null;
        }

        bool same = existing.Kind == kind && existing.ReportDefinitionId == definition?.Id && existing.ExportFormat == output.Format
                    && existing.ReportLanguage == output.Language && ReportRequestSnapshot.Parse(existing.RequestSnapshot).SameAs(snapshot);
        if (!same)
        {
            return AdministrationError.Rule(ReportErrorCodes.DuplicateRequest);
        }

        IReadOnlyDictionary<Guid, GeneratedOutput> outputs = await repository.ListOutputsAsync([existing.Id], cancellationToken).ConfigureAwait(false);
        return new ReportExportOutcome(ReportMapping.ToDetail(existing, definition?.Code, outputs.GetValueOrDefault(existing.Id)), Replayed: true);
    }
}

/// <summary>Jobs and outputs as the API presents them.</summary>
internal static class ReportMapping
{
    public static ReportJobDetail ToDetail(ReportJob job, ReportCode? code, GeneratedOutput? output)
    {
        ArgumentNullException.ThrowIfNull(job);
        return new ReportJobDetail(
            job.Id, job.Kind, code, job.ReportDefinitionId, job.ExportFormat, job.ReportLanguage, job.Status, job.RequestedAt, job.StartedAt, job.CompletedAt,
            job.FailureCode, job.CorrelationId,
            output is null ? null : new GeneratedOutputDetail(
                output.FileName, output.ContentType, output.SizeBytes, output.ChecksumSha256, output.Sensitivity, output.RowCount, output.SourceAsOf, output.ExpiresAt, output.Status));
    }

    public static ReportJobSummary ToSummary(ReportJob job, ReportCode? code, GeneratedOutput? output)
    {
        ArgumentNullException.ThrowIfNull(job);
        return new ReportJobSummary(job.Id, job.Kind, code, job.ExportFormat, job.Status, job.RequestedAt, job.CompletedAt, output?.Sensitivity, output?.ExpiresAt);
    }
}
