// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PMPlatform.Infrastructure.Persistence;

#nullable disable

namespace PMPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PMPlatformDbContext))]
    [Migration("20260925164521_TASK-025_CreateIdentityAccessTables")]
    partial class TASK025_CreateIdentityAccessTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PMPlatform.Domain.IdentityAccess.AccessRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("EndReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("end_reason");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid?>("ExternalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_entity_id");

                    b.Property<Guid>("PermissionProfileVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_profile_version_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("SponsorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sponsor_user_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_access_relationship");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_access_relationship_department_id");

                    b.HasIndex("ExternalEntityId")
                        .HasDatabaseName("ix_access_relationship_external_entity_id");

                    b.HasIndex("PermissionProfileVersionId")
                        .HasDatabaseName("ix_access_relationship_permission_profile_version_id");

                    b.HasIndex("SponsorUserId")
                        .HasDatabaseName("ix_access_relationship_sponsor_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_access_relationship_user_id");

                    b.ToTable("access_relationship", "identity_access", t =>
                        {
                            t.HasCheckConstraint("ck_access_relationship_end_reason", "\"end_reason\" IN ('PROJECT_CLOSED', 'ROLE_CHANGE', 'MIGRATED', 'MANUAL', 'EXPIRED')");

                            t.HasCheckConstraint("ck_access_relationship_status", "\"status\" IN ('ACTIVE', 'ENDED')");
                        });
                });

            modelBuilder.Entity("PMPlatform.Domain.IdentityAccess.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DirectoryReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("directory_reference");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_department_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "PMPlatform.Domain.IdentityAccess.Department.Name#BilingualLabel", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name_en");
                        });

                    b.HasKey("Id")
                        .HasName("pk_department");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_department_code");

                    b.HasIndex("ParentDepartmentId")
                        .HasDatabaseName("ix_department_parent_department_id");

                    b.ToTable("department", "identity_access");
                });

            modelBuilder.Entity("PMPlatform.Domain.IdentityAccess.ExternalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EntityTypeItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_type_item_id");

                    b.Property<Guid?>("SponsorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sponsor_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "PMPlatform.Domain.IdentityAccess.ExternalEntity.Name#BilingualLabel", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name_en");
                        });

                    b.HasKey("Id")
                        .HasName("pk_external_entity");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_external_entity_code");

                    b.HasIndex("SponsorUserId")
                        .HasDatabaseName("ix_external_entity_sponsor_user_id");

                    b.ToTable("external_entity", "identity_access", t =>
                        {
                            t.HasCheckConstraint("ck_external_entity_status", "\"status\" IN ('ACTIVE', 'SUSPENDED', 'RETIRED')");
                        });
                });

            modelBuilder.Entity("PMPlatform.Domain.IdentityAccess.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("DataClassificationItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_classification_item_id");

                    b.Property<bool>("IsPrivileged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_privileged");

                    b.Property<string>("PermissionGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission_group");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "PMPlatform.Domain.IdentityAccess.Permission.Name#BilingualLabel", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name_en");
                        });

                    b.HasKey("Id")
                        .HasName("pk_permission");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permission_code");

                    b.ToTable("permission", "identity_access");
                });

            modelBuilder.Entity("PMPlatform.Domain.IdentityAccess.PermissionProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BaseRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_role_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsShippedDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_shipped_default");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "PMPlatform.Domain.IdentityAccess.PermissionProfile.Name#BilingualLabel", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name_en");
                        });

                    b.HasKey("Id")
                        .HasName("pk_permission_profile");

                    b.HasIndex("BaseRoleId")
                        .HasDatabaseName("ix_permission_profile_base_role_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permission_profile_code");

                    b.ToTable("permission_profile", "identity_access");
                });

            modelBuilder.Entity("PMPlatform.Domain.IdentityAccess.PermissionProfileGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DataScope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("data_scope");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("PermissionProfileVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_profile_version_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_permission_profile_grant");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_permission_profile_grant_permission_id");

                    b.HasIndex("PermissionProfileVersionId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_permission_profile_grant_permission_profile_version_id_perm");

                    b.ToTable("permission_profile_grant", "identity_access", t =>
                        {
                            t.HasCheckConstraint("ck_permission_profile_grant_data_scope", "\"data_scope\" IN ('ALL', 'DEPT', 'OWN', 'ASSIGNED', 'ENTITY', 'READ_ONLY')");
                        });
                });

            modelBuilder.Entity("PMPlatform.Domain.IdentityAccess.PermissionProfileVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lifecycle_state");

                    b.Property<Guid>("PermissionProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_profile_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_user_id");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.Property<Guid?>("ValidatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("validated_by_user_id");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ChangeSummary", "PMPlatform.Domain.IdentityAccess.PermissionProfileVersion.ChangeSummary#NarrativeText", b1 =>
                        {
                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasColumnType("char(2)")
                                .HasColumnName("change_summary_lang");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("change_summary");
                        });

                    b.HasKey("Id")
                        .HasName("pk_permission_profile_version");

                    b.HasIndex("PublishedByUserId")
                        .HasDatabaseName("ix_permission_profile_version_published_by_user_id");

                    b.HasIndex("ValidatedByUserId")
                        .HasDatabaseName("ix_permission_profile_version_validated_by_user_id");

                    b.HasIndex("PermissionProfileId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("ix_permission_profile_version_permission_profile_id_version_no");

                    b.ToTable("permission_profile_version", "identity_access", t =>
                        {
                            t.HasCheckConstraint("ck_permission_profile_version_change_summary_lang", "\"change_summary_lang\" IN ('ar', 'en')");

                            t.HasCheckConstraint("ck_permission_profile_version_change_summary_pair", "(\"change_summary\" IS NULL) = (\"change_summary_lang\" IS NULL)");

                            t.HasCheckConstraint("ck_permission_profile_version_lifecycle_state", "\"lifecycle_state\" IN ('DRAFT', 'VALIDATED', 'PUBLISHED', 'RETIRED')");
                        });
                });

            modelBuilder.Entity("PMPlatform.Domain.IdentityAccess.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsExternalEligible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_external_eligible");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_system");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "PMPlatform.Domain.IdentityAccess.Role.Name#BilingualLabel", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name_en");
                        });

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_role_code");

                    b.ToTable("role", "identity_access");
                });

            modelBuilder.Entity("PMPlatform.Domain.IdentityAccess.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("DirectorySubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("directory_subject_id");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<Guid?>("ExternalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_entity_id");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_title");

                    b.Property<Guid?>("ManagerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_user_id");

                    b.Property<DateTimeOffset?>("MfaEnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mfa_enrolled_at");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mobile_number");

                    b.Property<DateTimeOffset?>("MobileVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mobile_verified_at");

                    b.Property<string>("NafathVerificationReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nafath_verification_reference");

                    b.Property<DateTimeOffset?>("NafathVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("nafath_verified_at");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(2)")
                        .HasDefaultValue("ar")
                        .HasColumnName("preferred_language");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_type");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_user_department_id");

                    b.HasIndex("DirectorySubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_directory_subject_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("ExternalEntityId")
                        .HasDatabaseName("ix_user_external_entity_id");

                    b.HasIndex("ManagerUserId")
                        .HasDatabaseName("ix_user_manager_user_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_user_username");

                    b.ToTable("user", "identity_access", t =>
                        {
                            t.HasCheckConstraint("ck_user_external_entity", "user_type <> 'EXTERNAL' OR external_entity_id IS NOT NULL");

                            t.HasCheckConstraint("ck_user_mobile_number", "mobile_number ~ '^\\+[1-9][0-9]{1,14}$'");

                            t.HasCheckConstraint("ck_user_preferred_language", "\"preferred_language\" IN ('ar', 'en')");

                            t.HasCheckConstraint("ck_user_status", "\"status\" IN ('ACTIVE', 'DISABLED')");

                            t.HasCheckConstraint("ck_user_user_type", "\"user_type\" IN ('INTERNAL', 'EXTERNAL', 'SERVICE')");
                        });
                });

            modelBuilder.Entity("PMPlatform.Domain.IdentityAccess.AccessRelationship", b =>
                {
                    b.HasOne("PMPlatform.Domain.IdentityAccess.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_access_relationship_department_department_id");

                    b.HasOne("PMPlatform.Domain.IdentityAccess.ExternalEntity", null)
                        .WithMany()
                        .HasForeignKey("ExternalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_access_relationship_external_entity_external_entity_id");

                    b.HasOne("PMPlatform.Domain.IdentityAccess.PermissionProfileVersion", null)
                        .WithMany()
                        .HasForeignKey("PermissionProfileVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_relationship_permission_profile_version_permission_p");

                    b.HasOne("PMPlatform.Domain.IdentityAccess.User", null)
                        .WithMany()
                        .HasForeignKey("SponsorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_access_relationship_user_sponsor_user_id");

                    b.HasOne("PMPlatform.Domain.IdentityAccess.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_relationship_user_user_id");
                });

            modelBuilder.Entity("PMPlatform.Domain.IdentityAccess.Department", b =>
                {
                    b.HasOne("PMPlatform.Domain.IdentityAccess.Department", null)
                        .WithMany()
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_department_department_parent_department_id");
                });

            modelBuilder.Entity("PMPlatform.Domain.IdentityAccess.ExternalEntity", b =>
                {
                    b.HasOne("PMPlatform.Domain.IdentityAccess.User", null)
                        .WithMany()
                        .HasForeignKey("SponsorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_external_entity_user_sponsor_user_id");
                });

            modelBuilder.Entity("PMPlatform.Domain.IdentityAccess.PermissionProfile", b =>
                {
                    b.HasOne("PMPlatform.Domain.IdentityAccess.Role", null)
                        .WithMany()
                        .HasForeignKey("BaseRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_permission_profile_role_base_role_id");
                });

            modelBuilder.Entity("PMPlatform.Domain.IdentityAccess.PermissionProfileGrant", b =>
                {
                    b.HasOne("PMPlatform.Domain.IdentityAccess.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_permission_profile_grant_permission_permission_id");

                    b.HasOne("PMPlatform.Domain.IdentityAccess.PermissionProfileVersion", null)
                        .WithMany()
                        .HasForeignKey("PermissionProfileVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permission_profile_grant_permission_profile_version_permiss");
                });

            modelBuilder.Entity("PMPlatform.Domain.IdentityAccess.PermissionProfileVersion", b =>
                {
                    b.HasOne("PMPlatform.Domain.IdentityAccess.PermissionProfile", null)
                        .WithMany()
                        .HasForeignKey("PermissionProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_permission_profile_version_permission_profile_permission_pr");

                    b.HasOne("PMPlatform.Domain.IdentityAccess.User", null)
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_permission_profile_version_user_published_by_user_id");

                    b.HasOne("PMPlatform.Domain.IdentityAccess.User", null)
                        .WithMany()
                        .HasForeignKey("ValidatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_permission_profile_version_user_validated_by_user_id");
                });

            modelBuilder.Entity("PMPlatform.Domain.IdentityAccess.User", b =>
                {
                    b.HasOne("PMPlatform.Domain.IdentityAccess.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_department_department_id");

                    b.HasOne("PMPlatform.Domain.IdentityAccess.ExternalEntity", null)
                        .WithMany()
                        .HasForeignKey("ExternalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_external_entity_external_entity_id");

                    b.HasOne("PMPlatform.Domain.IdentityAccess.User", null)
                        .WithMany()
                        .HasForeignKey("ManagerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_user_manager_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
